# Generated by Django 5.0.1 on 2025-02-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=10),
        ),
    ]
