# Generated by Django 5.0.1 on 2025-03-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_word_translation_alter_word_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
